// Firebase Cloud Function: askJarvisProxy.js
// Securely proxies user queries to the Gemini API, protected by App Check,
// and implements Firestore caching for static summaries (saving API quota).

const functions = require('firebase-functions/v1');
const {getApps, initializeApp} = require('firebase-admin/app');
const {getAppCheck} = require('firebase-admin/app-check');
const {getFirestore, FieldValue} = require('firebase-admin/firestore');
const https = require('https');

if (getApps().length === 0) {
  initializeApp();
}
const db = getFirestore();

exports.askJarvisProxy = functions.https.onRequest(async (req, res) => {
  // CORS Headers
  res.set('Access-Control-Allow-Origin', '*');
  if (req.method === 'OPTIONS') {
    res.set('Access-Control-Allow-Methods', 'POST');
    res.set('Access-Control-Allow-Headers', 'Content-Type, X-Firebase-AppCheck');
    return res.status(204).send('');
  }

  // 1. Enforce App Check
  const appCheckToken = req.header('X-Firebase-AppCheck');
  if (!appCheckToken) {
    return res.status(401).json({ error: 'App Check token is missing' });
  }

  try {
    await getAppCheck().verifyToken(appCheckToken);
  } catch (err) {
    console.error('App Check Token Verification Failed:', err);
    return res.status(401).json({ error: 'Unauthorized: Invalid App Check assertion' });
  }

  const { prompt, contextId, systemInstruction } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: 'Bad Request: Missing prompt parameter' });
  }

  // 2. Query Cache for Static Context (e.g. static proposals)
  if (contextId) {
    try {
      const cacheRef = db.collection('jarvis_cache').doc(contextId);
      const cacheSnap = await cacheRef.get();
      if (cacheSnap.exists) {
        const cachedData = cacheSnap.data();
        // Check if the prompt matches the cached prompt
        if (cachedData.prompt === prompt) {
          console.log(`[CACHE HIT] Serving response for Context ID: ${contextId}`);
          return res.status(200).json({ text: cachedData.response });
        }
      }
    } catch (cacheErr) {
      console.warn('Error reading from Firestore cache:', cacheErr);
    }
  }

  // 3. Retrieve GEMINI_KEY (stored securely in Cloud Secret Manager or environment)
  const GEMINI_KEY = process.env.GEMINI_KEY || functions.config().gemini?.key || '';
  if (!GEMINI_KEY) {
    return res.status(500).json({ error: 'Internal Server Error: Gemini credentials not configured' });
  }

  // 4. Construct Request to Gemini API
  const requestBody = JSON.stringify({
    system_instruction: { parts: [{ text: systemInstruction || "You are JARVIS, a helpful AI assistant." }] },
    contents: [{ role: 'user', parts: [{ text: prompt }] }]
  });

  try {
    const aiResponseText = await new Promise((resolve, reject) => {
      const gReq = https.request({
        hostname: 'generativelanguage.googleapis.com',
        path: `/v1beta/models/gemini-flash-latest:generateContent?key=${GEMINI_KEY}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(requestBody)
        }
      }, (gRes) => {
        let chunkData = '';
        gRes.on('data', chunk => chunkData += chunk);
        gRes.on('end', () => {
          try {
            const parsed = JSON.parse(chunkData);
            if (parsed.candidates && parsed.candidates[0].content.parts.length > 0) {
              resolve(parsed.candidates[0].content.parts.map(p => p.text).join(''));
            } else {
              reject(new Error('No response generated by model: ' + chunkData));
            }
          } catch (e) {
            reject(new Error('JSON parse error: ' + chunkData));
          }
        });
      });

      gReq.on('error', reject);
      gReq.write(requestBody);
      gReq.end();
    });

    // 5. Save to Cache if contextId is present
    if (contextId) {
      try {
        await db.collection('jarvis_cache').doc(contextId).set({
          contextId,
          prompt,
          response: aiResponseText,
          cachedAt: FieldValue.serverTimestamp()
        });
        console.log(`[CACHE SAVE] Saved response for Context ID: ${contextId}`);
      } catch (cacheWriteErr) {
        console.warn('Error saving to cache:', cacheWriteErr);
      }
    }

    return res.status(200).json({ text: aiResponseText });

  } catch (apiError) {
    console.error('Gemini API request failed:', apiError);
    return res.status(502).json({ error: 'Bad Gateway: AI model query failed: ' + apiError.message });
  }
});
