/* Society formation, clerk mandates, recall and federation — authority remains with members. */
(function(){
  'use strict';
  if(!window.GAIGSConstitutionLogic)return;
  const C=window.GAIGSConstitutionLogic;
  const uid=()=>fbAuth?.currentUser?.uid||state.user?.uid||state.user?.email||'offline-member';
  const cloudReady=()=>Boolean(firebaseAvailable&&window.NDCONF?.firebaseProductionMode===true&&fbAuth?.currentUser&&fbDb);
  const rid=prefix=>`${prefix}_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`;
  const statusClass=value=>['active','approved','elected'].includes(String(value).toLowerCase())?'green':['rejected','recalled'].includes(String(value).toLowerCase())?'red':'gold';
  function policyTable(){
    const p=C.POLICY;
    return `<div class="constitution-grid"><div class="rule-card"><h4>Society formation</h4><p>${p.formation.minimumFounders} verified residents · ${p.formation.boundaryEvidenceMinimum} independent boundary proofs · ${p.formation.quorumPercent}% quorum · ${p.formation.approvalPercent}% approval.</p></div><div class="rule-card"><h4>Elected clerks</h4><p>${p.clerk.termDays}-day term · ${p.clerk.maximumConsecutiveTerms} consecutive terms maximum · ${p.clerk.quorumPercent}% election quorum.</p></div><div class="rule-card"><h4>Member recall</h4><p>${p.recall.petitionPercent}% recall petition · ${p.recall.quorumPercent}% vote quorum · majority removes the clerk.</p></div><div class="rule-card"><h4>Federation</h4><p>Society delegates carry a published mandate to city coordination and remain recallable. Higher scope coordinates; it does not own lower scopes.</p></div></div>`;
  }
  function petitionCard(item){
    const founders=Array.isArray(item.founders)?item.founders:[],verified=founders.filter(x=>x.residenceVerified&&x.inBoundary).length,needed=Math.max(0,C.POLICY.formation.minimumFounders-verified);
    return `<article class="proposal-item"><div class="governance-record-head"><div><span class="tag ${statusClass(item.status)}">${esc(String(item.status||'petition').toUpperCase())}</span><h3>${esc(item.name)}</h3></div><span class="tag">${esc(item.area||'Boundary pending')}</span></div><p class="muted">${esc(item.purpose||'Resident-led local coordination.')}</p><div class="metric-row"><div class="metric"><small>Verified founders</small><b>${verified}/${C.POLICY.formation.minimumFounders}</b></div><div class="metric"><small>Boundary proofs</small><b>${(item.boundaryEvidence||[]).filter(x=>x.verified).length}/${C.POLICY.formation.boundaryEvidenceMinimum}</b></div><div class="metric"><small>Next step</small><b>${needed?`${needed} residents`:'Boundary review'}</b></div></div><div class="rule-actions"><button class="ghost-btn" data-petition-join="${esc(item.id)}">Join petition</button><button class="ghost-btn" data-petition-audit="${esc(item.id)}">Formation audit</button></div></article>`;
  }
  function mandateCard(item){
    return `<div class="activity-item"><div class="activity-icon">CL</div><div><b>${esc(item.name||item.memberId||'Elected clerk')}</b><p>${esc(item.scope||'Society')} · term ${esc(item.termEndsAt||'pending')} · ${esc(item.mandate||'Publish records and coordinate approved work')}</p><span class="tag ${statusClass(item.status)}">${esc(String(item.status||'active').toUpperCase())}</span><button class="mini-btn" data-clerk-recall="${esc(item.id)}">Start recall petition</button></div></div>`;
  }
  views.constitution=function(){
    const petitions=state.societyPetitions||[],mandates=state.clerkMandates||[];
    return `${pageHead('People-first constitution','Default platform law for society formation, elected clerks, recall and federation. Applicable public law always prevails.',`<button class="action-btn" data-formation-start>＋ Form a society</button>`)}<div class="capability-strip"><span class="tag green">${esc(C.VERSION)}</span><b>Clerks serve; members decide</b><span>No clerk can cast your vote, change an outcome or release project funds.</span></div><div class="dashboard-grid">${card('Constitution defaults',policyTable(),12)}<section class="card span-8"><div class="card-head"><div class="card-title">Formation petitions</div></div><div class="card-body proposal-list">${petitions.length?petitions.map(petitionCard).join(''):'<div class="empty-state"><h3>No formation petition yet</h3><p>Ten verified residents can request a non-overlapping society boundary and then ratify it by vote.</p></div>'}</div></section>${card('Elected clerk mandates',mandates.length?`<div class="activity-list">${mandates.map(mandateCard).join('')}</div>`:'<div class="empty-state"><h3>No active mandate loaded</h3><p>Clerks appear only after a completed member election.</p></div>',4)}${card('Clerk authority boundary',`<div class="authority-grid"><div><b>May coordinate</b><span>${C.CLERK_ACTIONS.map(x=>esc(x.replaceAll('_',' '))).join(' · ')}</span></div><div><b>Never may</b><span>${C.RESERVED_ACTIONS.map(x=>esc(x.replaceAll('_',' '))).join(' · ')}</span></div></div>`,12)}</div>`;
  };
  function formationForm(){
    return `<h2>Request society formation</h2><p class="muted">This creates a petition, not an authority. Other residents must independently verify and join it.</p><form id="societyFormationForm" class="form-grid"><label>Proposed society name<input id="formationName" maxlength="120" required></label><label>Neighbourhood / boundary summary<textarea id="formationArea" maxlength="800" required></textarea></label><label>Public society centre<input id="formationCenter" maxlength="200" placeholder="Community hall, market or public landmark" required></label><label>Purpose<textarea id="formationPurpose" maxlength="1200" required></textarea></label><label>Private residence evidence reference<input id="formationEvidence" maxlength="240" required></label><label class="consent"><input id="formationDeclaration" type="checkbox" required> I live inside this proposed boundary and consent to an authorized reviewer checking this claim. Exact home location stays private.</label><button class="primary">Create resident petition</button></form>`;
  }
  async function submitFormation(event){
    event.preventDefault();event.stopImmediatePropagation();
    if(cloudReady()&&state.user?.kycStatus!=='verified')return toast('Verified identity and residence review are required for a live petition.');
    const record={id:rid('society_petition'),name:$('#formationName').value.trim(),area:$('#formationArea').value.trim(),center:$('#formationCenter').value.trim(),purpose:$('#formationPurpose').value.trim(),status:'verification',createdBy:uid(),founders:[{memberId:uid(),residenceEvidenceRef:$('#formationEvidence').value.trim(),residenceVerified:!cloudReady(),inBoundary:!cloudReady(),joinedAt:new Date().toISOString()}],boundaryEvidence:[],overlapResolved:false,constitutionVersion:C.VERSION,createdAt:new Date().toISOString()};
    try{if(cloudReady()){const petitionRef=fbDb.collection('societyPetitions').doc(record.id),batch=fbDb.batch(),now=firebase.firestore.FieldValue.serverTimestamp();batch.set(petitionRef,{...record,founders:[],createdAt:now});batch.set(petitionRef.collection('founders').doc(uid()),{memberId:uid(),residenceEvidenceRef:$('#formationEvidence').value.trim(),residenceVerified:false,inBoundary:false,joinedAt:now});await batch.commit();}state.societyPetitions.unshift(record);save();closeModal();navigate('constitution');toast(cloudReady()?'Petition submitted for residence and boundary review.':'Preview petition created; no public verification occurred.');}catch(error){toast(error.message||'Petition could not be created.');}
  }
  function openJoin(petitionId){
    const item=state.societyPetitions.find(x=>x.id===petitionId);if(!item)return;
    if((item.founders||[]).some(x=>x.memberId===uid()))return toast('This account already joined the petition.');
    openModal(`<h2>Join ${esc(item.name)}</h2><form id="petitionJoinForm" class="form-grid"><label>Private residence evidence reference<input id="petitionEvidence" required maxlength="240"></label><label class="consent"><input type="checkbox" required> I live inside the proposed boundary and consent to reviewer verification.</label><button class="primary">Join as a founding resident</button></form>`);
    $('#petitionJoinForm').addEventListener('submit',async event=>{event.preventDefault();const founder={memberId:uid(),residenceEvidenceRef:$('#petitionEvidence').value.trim(),residenceVerified:!cloudReady(),inBoundary:!cloudReady(),joinedAt:new Date().toISOString()};try{if(cloudReady())await fbDb.collection('societyPetitions').doc(item.id).collection('founders').doc(uid()).set({...founder,joinedAt:firebase.firestore.FieldValue.serverTimestamp()});item.founders=[...(item.founders||[]),founder];save();closeModal();render();toast(cloudReady()?'Founder claim submitted for independent review.':'Preview founder added; no public verification occurred.');}catch(error){toast(error.message||'Petition join failed.');}});
  }
  function auditPetition(id){
    const item=state.societyPetitions.find(x=>x.id===id);if(!item)return;
    const result=C.evaluateFormation({founders:item.founders,boundaryEvidence:item.boundaryEvidence,overlapResolved:item.overlapResolved,vote:item.vote||{eligible:(item.founders||[]).length}});
    openModal(`<h2>Formation audit</h2><div class="rule-card"><p><b>Constitution:</b> ${esc(result.version)}</p><p><b>Founder verification:</b> ${result.founders.valid?'ready':'incomplete'}</p><p><b>Boundary evidence:</b> ${result.boundaryValid?'ready':'incomplete'}</p><p><b>Overlap/appeal:</b> ${result.noOverlap?'resolved':'pending'}</p><p><b>Ratification vote:</b> ${result.vote.passed?'passed':'not passed'}</p></div><p class="muted">${esc(result.reasons.join(' ')||'All default formation conditions are satisfied. Server review still checks applicable local law.')}</p>`);
  }
  function recall(id){
    const mandate=state.clerkMandates.find(x=>x.id===id);if(!mandate)return;
    openModal(`<h2>Start recall petition</h2><p class="muted">A clerk is a recallable service role. A petition does not remove them until the threshold and member vote both pass.</p><form id="recallForm" class="form-grid"><label>Public reason<textarea id="recallReason" required maxlength="1200"></textarea></label><label>Evidence reference<input id="recallEvidence" required maxlength="240"></label><button class="primary">Sign recall petition</button></form>`);
    $('#recallForm').addEventListener('submit',event=>{event.preventDefault();mandate.recallPetition=mandate.recallPetition||{signatures:[],status:'collecting'};if(!mandate.recallPetition.signatures.includes(uid()))mandate.recallPetition.signatures.push(uid());mandate.recallPetition.reason=$('#recallReason').value.trim();mandate.recallPetition.evidence=$('#recallEvidence').value.trim();save();closeModal();render();toast('Recall signature recorded; member vote opens only after the threshold.');});
  }
  const baseBindDynamic=bindDynamic;
  bindDynamic=function(){baseBindDynamic();$$('[data-formation-start]').forEach(button=>button.addEventListener('click',()=>openModal(formationForm())));$$('[data-petition-join]').forEach(button=>button.addEventListener('click',()=>openJoin(button.dataset.petitionJoin)));$$('[data-petition-audit]').forEach(button=>button.addEventListener('click',()=>auditPetition(button.dataset.petitionAudit)));$$('[data-clerk-recall]').forEach(button=>button.addEventListener('click',()=>recall(button.dataset.clerkRecall)));};
  const baseBindModal=bindModal;
  bindModal=function(){baseBindModal();const form=$('#societyFormationForm');if(form&&!form.dataset.bound){form.dataset.bound='1';form.addEventListener('submit',submitFormation,true);}};
  viewNames.constitution='Constitution & society formation';
})();
