/* Society administration: membership review, roles, moderation and append-only audit records. */
(function(){
  'use strict';
  const cloud=()=>Boolean(firebaseAvailable&&window.NDCONF?.firebaseProductionMode===true&&fbAuth?.currentUser&&fbDb);
  const uid=()=>fbAuth?.currentUser?.uid||state.user?.uid||state.user?.email||'offline-user';
  const makeId=(p='event')=>`${p}_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`;
  const stored=JSON.parse(localStorage.getItem('gaigsCommunityAdminV1')||'null')||{};
  const adminState={selectedId:stored.selectedId||'',requests:stored.requests||[],members:stored.members||[],audit:stored.audit||[],reports:stored.reports||[],loading:false};
  const persist=()=>localStorage.setItem('gaigsCommunityAdminV1',JSON.stringify(adminState));
  viewNames.communityAdmin='Society administration';
  function ownedCommunities(){return (state.communities||[]).filter(c=>c.ownerId===uid()||c.role==='admin'||c.role==='committee');}
  function selected(){return ownedCommunities().find(c=>c.id===adminState.selectedId)||ownedCommunities()[0]||null;}
  function audit(action,subjectId,details){const item={id:makeId('audit'),action,subjectId,details,actorId:uid(),actorName:state.user?.name||'Administrator',createdAt:new Date().toISOString()};adminState.audit.unshift(item);persist();const community=selected();if(cloud()&&community)fbDb.collection('communities').doc(community.id).collection('audit').doc(item.id).set({...item,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{});}
  function roleBadge(role){return `<span class="tag ${role==='admin'?'gold':'green'}">${esc(String(role||'member').toUpperCase())}</span>`;}
  function requestRows(community){
    const list=adminState.requests.filter(r=>r.communityId===community.id&&['pending','needs_more_evidence'].includes(r.status));
    if(!list.length)return '<div class="empty-message">No pending membership requests.</div>';
    return list.map(r=>`<div class="admin-request"><div class="activity-icon">${esc((r.userName||'M').slice(0,2).toUpperCase())}</div><div class="admin-request-copy"><b>${esc(r.userName||r.userId||'Applicant')}</b><p>${esc(r.residenceStatus||'Resident')} · ${esc(r.area||'Area not supplied')}</p><div class="private-evidence"><small>PRIVATE EVIDENCE REFERENCE</small><span>${esc(r.evidenceRef||'Not supplied')}</span></div><div class="rule-actions"><button class="action-btn" data-member-decision="approved" data-request-id="${esc(r.id||r.userId)}">Approve</button><button class="ghost-btn" data-member-decision="needs_more_evidence" data-request-id="${esc(r.id||r.userId)}">Ask evidence</button><button class="ghost-btn danger" data-member-decision="rejected" data-request-id="${esc(r.id||r.userId)}">Reject</button></div></div></div>`).join('');
  }
  function memberRows(community){
    const list=adminState.members.filter(m=>m.communityId===community.id&&m.status==='active');
    if(!list.length)return '<div class="empty-message">Creator account is the first administrator.</div>';
    return list.map(m=>`<div class="member-item"><div class="activity-icon">${esc((m.userName||'M').slice(0,2).toUpperCase())}</div><div><b>${esc(m.userName||m.userId)}</b><p>Active member · joined ${esc(m.joinedAt||'recently')}</p></div>${roleBadge(m.role)}${m.userId!==uid()?`<select class="role-select" data-member-role="${esc(m.userId)}">${GAIGSCommunityLogic.roles.map(role=>`<option ${role===m.role?'selected':''}>${role}</option>`).join('')}</select>`:''}</div>`).join('');
  }
  function reportRows(community){
    const localSocial=JSON.parse(localStorage.getItem('gaigsSocialV1')||'{}');const reports=[...adminState.reports,...(localSocial.reports||[]).filter(r=>!r.communityId||r.communityId===community.id)].filter(r=>!r.status||r.status==='open');
    if(!reports.length)return '<div class="empty-message">No open moderation reports.</div>';
    return reports.map(r=>`<div class="activity-item"><div class="activity-icon">!</div><div><b>Reported content ${esc(r.postId||'')}</b><p>${esc(r.reason||'Review requested')}</p><div class="rule-actions"><button class="mini-btn" data-report-resolution="no_violation" data-report-id="${esc(r.id)}">No violation</button><button class="mini-btn" data-report-resolution="restricted" data-report-id="${esc(r.id)}">Restrict locally</button><button class="mini-btn" data-report-resolution="escalated" data-report-id="${esc(r.id)}">Escalate</button></div></div></div>`).join('');
  }
  function auditRows(){return adminState.audit.slice(0,20).map(a=>`<div class="transaction-item"><div class="activity-icon">✓</div><div><b>${esc(a.action)}</b><p class="muted">${esc(a.actorName)} · ${new Date(a.createdAt).toLocaleString()} · ${esc(a.details||'')}</p></div></div>`).join('')||'<div class="empty-message">Administrative actions will appear here.</div>';}
  views.communityAdmin=function(){
    const communities=ownedCommunities(),community=selected();
    if(!community)return `${pageHead('Society administration','Register a society first. Its creator receives the initial administrator role.',`<button class="action-btn" data-action="community">＋ Register society</button>`)}${card('No managed society',`<div class="briefing">Administrators review residence requests, assign limited roles, moderate reports and preserve an audit trail. No person becomes an active member automatically.</div>`,12)}`;
    return `${pageHead('Society administration',`Manage ${esc(community.name)} with role separation and auditable decisions.`,`<select class="admin-community-select">${communities.map(c=>`<option value="${esc(c.id)}" ${c.id===community.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select><button class="ghost-btn" data-admin-refresh>Refresh</button>`)}<div class="admin-privacy-warning">Residence evidence is private. Do not copy it into posts, public audit descriptions or JARVIS prompts.</div><div class="dashboard-grid">${card('Pending membership review',requestRows(community),7)}${card('Decision rules',`<div class="rule-card"><h4>Approval</h4><p>Confirm society boundary and evidence. Approval creates a normal member role only.</p></div><div class="rule-card" style="margin-top:8px"><h4>Rejection and appeal</h4><p>A recorded reason is mandatory. Applicants must have an appeal route.</p></div><div class="rule-card" style="margin-top:8px"><h4>Role separation</h4><p>Treasurer, moderator and committee permissions stay distinct.</p></div>`,5)}${card('Active members and roles',memberRows(community),7)}${card('Moderation queue',reportRows(community),5)}${card('Append-only administration history',auditRows(),12)}</div>`;
  };
  async function loadCloud(){
    const community=selected();if(!cloud()||!community||adminState.loading)return;adminState.loading=true;
    try{const [members,reports]=await Promise.all([fbDb.collection('communities').doc(community.id).collection('members').limit(500).get(),fbDb.collection('contentReports').where('communityId','==',community.id).limit(100).get()]);adminState.requests=adminState.requests.filter(x=>x.communityId!==community.id);adminState.members=adminState.members.filter(x=>x.communityId!==community.id);members.forEach(doc=>{const value={id:doc.id,userId:doc.id,communityId:community.id,...doc.data()};if(['pending','needs_more_evidence'].includes(value.status))adminState.requests.push(value);else if(value.status==='active')adminState.members.push(value);});adminState.reports=adminState.reports.filter(x=>x.communityId!==community.id);reports.forEach(doc=>adminState.reports.push({id:doc.id,...doc.data()}));persist();if(state.view==='communityAdmin')render();}catch(error){toast(error.message||'Could not load society records.');}finally{adminState.loading=false;}
  }
  function decisionForm(request,decision){
    const requiresReason=decision!=='approved';openModal(`<h2>${decision==='approved'?'Approve member':decision==='rejected'?'Reject request':'Request more evidence'}</h2><p class="muted">This decision is recorded in the society audit history.</p><form id="membershipDecisionForm" class="form-grid"><label>Decision reason<textarea id="decisionReason" ${requiresReason?'required':''} placeholder="State evidence checked or a clear reason..."></textarea></label><label class="consent"><input type="checkbox" required> I reviewed the correct applicant and society.</label><button class="primary">Confirm decision</button></form>`);
    $('#membershipDecisionForm').addEventListener('submit',async event=>{event.preventDefault();try{const updated=GAIGSCommunityLogic.reviewRequest(request,decision,$('#decisionReason').value,uid()),community=selected();if(cloud()){await fbDb.collection('communities').doc(community.id).collection('members').doc(request.userId||request.id).update({status:updated.status,role:updated.role,reviewReason:updated.reviewReason,reviewedBy:uid(),reviewedAt:firebase.firestore.FieldValue.serverTimestamp()});}adminState.requests=adminState.requests.map(r=>r===request?updated:r);if(updated.status==='active')adminState.members.push({...updated,communityId:community.id});audit(`Membership ${decision}`,request.userId||request.id,updated.reviewReason||'Evidence reviewed');persist();closeModal();render();toast(`Membership ${decision}.`);}catch(error){toast(error.message||'Decision failed.');}});
  }
  async function changeRole(userId,role){if(!GAIGSCommunityLogic.validRole(role))return;const community=selected(),member=adminState.members.find(m=>m.communityId===community.id&&m.userId===userId);if(!member)return;try{if(cloud())await fbDb.collection('communities').doc(community.id).collection('members').doc(userId).update({role,roleUpdatedBy:uid(),roleUpdatedAt:firebase.firestore.FieldValue.serverTimestamp()});member.role=role;audit('Member role changed',userId,`Role set to ${role}`);persist();toast('Member role updated.');}catch(error){toast(error.message||'Role update failed.');}}
  async function resolveReport(reportId,resolution){const report=adminState.reports.find(r=>r.id===reportId);try{if(cloud()&&report)await fbDb.collection('contentReports').doc(reportId).update({status:resolution,resolvedBy:uid(),resolvedAt:firebase.firestore.FieldValue.serverTimestamp()});if(report){report.status=resolution;report.resolvedBy=uid();report.resolvedAt=new Date().toISOString();}const local=JSON.parse(localStorage.getItem('gaigsSocialV1')||'{}');if(Array.isArray(local.reports)){const item=local.reports.find(r=>r.id===reportId);if(item)item.status=resolution;localStorage.setItem('gaigsSocialV1',JSON.stringify(local));}audit('Moderation report resolved',reportId,resolution);persist();render();toast(`Report marked ${resolution}.`);}catch(error){toast(error.message||'Report resolution failed.');}}
  const baseBindDynamic=bindDynamic;
  bindDynamic=function(){baseBindDynamic();$('.admin-community-select')?.addEventListener('change',event=>{adminState.selectedId=event.target.value;persist();render();loadCloud();});$$('[data-admin-refresh]').forEach(b=>b.addEventListener('click',loadCloud));$$('[data-member-decision]').forEach(b=>b.addEventListener('click',()=>{const request=adminState.requests.find(r=>(r.id||r.userId)===b.dataset.requestId);if(request)decisionForm(request,b.dataset.memberDecision);}));$$('[data-member-role]').forEach(s=>s.addEventListener('change',()=>changeRole(s.dataset.memberRole,s.value)));$$('[data-report-resolution]').forEach(b=>b.addEventListener('click',()=>resolveReport(b.dataset.reportId,b.dataset.reportResolution)));if(state.view==='communityAdmin')setTimeout(loadCloud,0);};
  const baseBindModal=bindModal;
  bindModal=function(){baseBindModal();const form=$('#communityCreateForm');if(!form||form.dataset.adminBound)return;form.dataset.adminBound='1';form.addEventListener('submit',async event=>{event.preventDefault();event.stopImmediatePropagation();try{const clean=GAIGSCommunityLogic.sanitizeCommunity({name:$('#communityName').value,location:$('#communityLocation').value,purpose:form.querySelector('textarea')?.value,level:$('#communityLevel').value}),id=makeId('society'),shareCenter=Boolean($('#communityShareCenter')?.checked&&Number.isFinite(Number(state.user?.lat))&&Number.isFinite(Number(state.user?.lng)));const community={id,...clean,ownerId:uid(),createdBy:uid(),role:'admin',status:'active',members:1,city:state.user?.city||'',country:state.user?.country||'',lat:shareCenter?Number(state.user.lat):null,lng:shareCenter?Number(state.user.lng):null,coordinateType:shareCenter?'public_center':'none',createdAt:new Date().toISOString()};if(cloud()){await fbDb.collection('communities').doc(id).set({...community,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await fbDb.collection('communities').doc(id).collection('members').doc(uid()).set({userId:uid(),userName:state.user.name,status:'active',role:'admin',joinedAt:firebase.firestore.FieldValue.serverTimestamp()});}state.communities.unshift(community);adminState.selectedId=id;adminState.members.push({communityId:id,userId:uid(),userName:state.user.name,status:'active',role:'admin',joinedAt:'Today'});save();audit('Society registered',id,clean.location);persist();closeModal();navigate('communityAdmin');toast('Society registered; administration workspace opened.');}catch(error){toast(error.message||'Society registration failed.');}},true);};
  const baseReportPost=typeof reportPost==='function'?reportPost:null;
  if(baseReportPost)reportPost=function(post){const community=selected();if(cloud()&&community)fbDb.collection('contentReports').add({postId:post.id,communityId:community.id,reporterId:uid(),reason:'User requested review',status:'open',createdAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(()=>{});return baseReportPost(post);};
  if(state.user)render();
})();
