/* Optional user-owned Ethereum testnet governance. No browser-generated or custodial private keys. */
(function(){
  'use strict';
  const cfg=()=>window.NDCONF?.ethereum||{};
  const enabled=()=>Boolean(cfg().governorAddress&&/^0x[a-fA-F0-9]{40}$/.test(cfg().governorAddress));
  const short=value=>value?`${value.slice(0,6)}…${value.slice(-4)}`:'Not connected';
  function chainLabel(chainId){const expected=String(cfg().chainId||'11155111');return String(parseInt(chainId||'0',16)||chainId)===expected?(cfg().chainName||'Ethereum testnet'):`Chain ${parseInt(chainId||'0',16)||chainId||'unknown'}`;}
  function receiptRows(){const rows=state.dao?.receipts||[];return rows.length?`<div class="activity-list">${rows.slice(0,20).map(row=>`<div class="activity-item"><div class="activity-icon">Ξ</div><div><b>${esc(row.type)}</b><p><span class="mono">${esc(short(row.hash))}</span> · ${esc(row.status||'submitted')} · ${esc(row.chain||'')}</p></div></div>`).join('')}</div>`:'<div class="empty-state"><h3>No wallet receipts</h3><p>Confirmed testnet transactions will appear here.</p></div>';}
  views.dao=function(){
    const connected=state.dao?.walletAddress,configured=enabled(),expected=cfg().chainName||'Sepolia';
    return `${pageHead('Ethereum civic DAO','One verified wallet, one vote; timelocked execution; public project vaults; private identity and individual ballot details stay off-chain.',`<button class="action-btn" data-dao-connect>${connected?'Reconnect wallet':'Connect my wallet'}</button>`)}<div class="capability-strip"><span class="tag ${configured?'green':'gold'}">${configured?'TESTNET CONTRACTS CONFIGURED':'CONTRACT DEPLOYMENT REQUIRED'}</span><b>${esc(short(connected))}</b><span>${esc(chainLabel(state.dao?.chainId))}</span></div><div class="dashboard-grid">${card('Your user-owned wallet',`<div class="wallet-balance"><div><small>Address</small><div class="mono">${esc(connected||'Connect only when you choose')}</div></div><span class="tag ${connected?'green':'gold'}">${connected?'CONNECTED':'OPTIONAL'}</span></div><p class="muted">GAIGS never asks for your seed phrase and never stores a private key. The platform account and crypto wallet are separate.</p><button class="ghost-btn" data-dao-connect>${connected?'Refresh connection':'Connect wallet'}</button>`,5)}${card('DAO contract set',`<div class="activity-list"><div class="activity-item"><div class="activity-icon">1V</div><div><b>Verified member registry</b><p>Pseudonymous wallet eligibility snapshots; no CNIC, phone, email or home address.</p></div></div><div class="activity-item"><div class="activity-icon">GV</div><div><b>Civic governor</b><p>One address, one ballot; quorum, approval and execution delay enforced by contract.</p></div></div><div class="activity-item"><div class="activity-icon">PV</div><div><b>Project vault</b><p>Project-specific deposits, evidence hashes and governance-only milestone releases.</p></div></div></div>`,7)}${card('On-chain member action',configured?`<div class="rule-card"><h4>${esc(expected)} release candidate</h4><p>Use only deployed, verified and externally audited addresses. Mainnet actions remain disabled unless the production flag is intentionally enabled.</p></div><div class="rule-actions"><button class="action-btn" data-dao-propose ${connected?'':'disabled'}>Anchor an approved decision</button><button class="ghost-btn" data-dao-vote ${connected?'':'disabled'}>Cast DAO ballot</button></div>`:`<div class="empty-state"><h3>Deploy audited testnet contracts</h3><p>Compile and deploy the production-direction contract set, verify source code, then place addresses in server-generated configuration.</p></div>`,6)}${card('Wallet transaction receipts',receiptRows(),6)}${card('Safety model',`<div class="rule-card"><h4>No wealth voting</h4><p>Tokens and wallet balances do not increase voting power.</p></div><div class="rule-card"><h4>No instant execution</h4><p>Passing actions enter a public timelock before execution.</p></div><div class="rule-card"><h4>No hidden identity leak</h4><p>Identity and residence verification remain encrypted off-chain; only eligibility is represented on-chain.</p></div>`,12)}</div>`;
  };
  async function provider(){if(!window.ethereum)throw new Error('Install or open an EIP-1193 compatible wallet.');if(!window.ethers)throw new Error('Ethereum client library did not load.');return new ethers.BrowserProvider(window.ethereum);}
  async function connect(){try{const p=await provider(),accounts=await p.send('eth_requestAccounts',[]),network=await p.getNetwork();state.dao=state.dao||{receipts:[]};state.dao.walletAddress=accounts[0]||'';state.dao.chainId=network.chainId.toString();save();render();toast(`Wallet connected on ${chainLabel(state.dao.chainId)}.`);}catch(error){toast(error.message||'Wallet connection failed.');}}
  function ensureWritable(){if(!enabled())throw new Error('DAO contract addresses are not configured.');if(!state.dao?.walletAddress)throw new Error('Connect your wallet first.');if(String(state.dao.chainId)!==String(cfg().chainId))throw new Error(`Switch your wallet to ${cfg().chainName||'the configured testnet'}.`);if(String(cfg().chainId)==='1'&&cfg().mainnetEnabled!==true)throw new Error('Mainnet actions are disabled for this release candidate.');}
  function governor(signer){return new ethers.Contract(cfg().governorAddress,["function hashActions(address[] targets,uint256[] values,bytes[] calldatas) pure returns (bytes32)","function propose(bytes32 metadataHash,bytes32 actionsHash) returns (uint256)","function castVote(uint256 proposalId,uint8 choice)","event ProposalCreated(uint256 indexed proposalId,address indexed proposer,bytes32 metadataHash,bytes32 actionsHash,uint48 voteStart,uint48 voteEnd,uint64 eligibleSnapshot)"],signer);}
  function proposeModal(){const approved=(state.proposals||[]).filter(item=>String(item.status).toLowerCase()==='approved');openModal(`<h2>Anchor an approved civic decision</h2><p class="muted">This opens an on-chain proposal with no automatic fund movement. Later actions must match a separately reviewed action hash.</p><form id="daoProposalForm" class="form-grid"><label>Approved decision<select id="daoLocalProposal" ${approved.length?'':'disabled'}>${approved.map(item=>`<option value="${esc(item.id)}">${esc(item.title)}</option>`).join('')||'<option>No approved decision loaded</option>'}</select></label><label class="consent"><input type="checkbox" required> I reviewed the proposal, network and wallet confirmation.</label><button class="primary" ${approved.length?'':'disabled'}>Create testnet proposal</button></form>`);}
  function voteModal(){openModal(`<h2>Cast DAO ballot</h2><form id="daoVoteForm" class="form-grid"><label>On-chain proposal ID<input id="daoProposalId" type="number" min="1" step="1" required></label><label>Ballot<select id="daoVoteChoice"><option value="1">For</option><option value="0">Against</option><option value="2">Abstain</option></select></label><label class="consent"><input type="checkbox" required> My wallet will show the exact testnet transaction before I approve it.</label><button class="primary">Review in wallet</button></form>`);}
  async function submitProposal(event){event.preventDefault();event.stopImmediatePropagation();try{ensureWritable();const item=state.proposals.find(x=>String(x.id)===$('#daoLocalProposal').value);if(!item)throw new Error('Approved decision not found.');const p=await provider(),signer=await p.getSigner(),contract=governor(signer),metadataHash=ethers.keccak256(ethers.toUtf8Bytes(JSON.stringify({id:item.id,title:item.title,scope:item.scope,scopeId:item.scopeId,rulesVersion:item.rulesVersion}))),actionsHash=await contract.hashActions([],[],[]),tx=await contract.propose(metadataHash,actionsHash);state.dao.receipts=state.dao.receipts||[];state.dao.receipts.unshift({type:'DAO proposal',hash:tx.hash,status:'submitted',chain:cfg().chainName,createdAt:new Date().toISOString()});save();closeModal();render();toast('Proposal submitted; wait for network confirmation.');tx.wait().then(()=>{const row=state.dao.receipts.find(x=>x.hash===tx.hash);if(row){row.status='confirmed';save();if(state.view==='dao')render();}});}catch(error){toast(error.shortMessage||error.message||'DAO proposal failed.');}}
  async function submitVote(event){event.preventDefault();event.stopImmediatePropagation();try{ensureWritable();const p=await provider(),signer=await p.getSigner(),tx=await governor(signer).castVote(BigInt($('#daoProposalId').value),Number($('#daoVoteChoice').value));state.dao.receipts=state.dao.receipts||[];state.dao.receipts.unshift({type:'DAO ballot',hash:tx.hash,status:'submitted',chain:cfg().chainName,createdAt:new Date().toISOString()});save();closeModal();render();toast('Ballot submitted; wait for network confirmation.');tx.wait().then(()=>{const row=state.dao.receipts.find(x=>x.hash===tx.hash);if(row){row.status='confirmed';save();if(state.view==='dao')render();}});}catch(error){toast(error.shortMessage||error.message||'DAO ballot failed.');}}
  const baseBindDynamic=bindDynamic;
  bindDynamic=function(){baseBindDynamic();$$('[data-dao-connect]').forEach(button=>button.addEventListener('click',connect));$$('[data-dao-propose]').forEach(button=>button.addEventListener('click',proposeModal));$$('[data-dao-vote]').forEach(button=>button.addEventListener('click',voteModal));};
  const baseBindModal=bindModal;
  bindModal=function(){baseBindModal();const proposal=$('#daoProposalForm'),voteForm=$('#daoVoteForm');if(proposal&&!proposal.dataset.bound){proposal.dataset.bound='1';proposal.addEventListener('submit',submitProposal,true);}if(voteForm&&!voteForm.dataset.bound){voteForm.dataset.bound='1';voteForm.addEventListener('submit',submitVote,true);}};
  viewNames.dao='Ethereum civic DAO';
})();
