/* Honest home, profile, projects, global and crew views built from current records only. */
(function(){
  'use strict';
  const cloudReady=()=>Boolean(firebaseAvailable&&window.NDCONF?.firebaseProductionMode===true&&fbAuth?.currentUser&&fbDb);
  const status=value=>String(value||'').toLowerCase();
  function recordList(items,empty){return items.length?`<div class="activity-list">${items.map(item=>`<div class="activity-item"><div class="activity-icon">${esc(item.icon||'•')}</div><div><b>${esc(item.title)}</b><p>${esc(item.detail||'')}</p>${item.tag?`<span class="tag ${item.tagClass||''}">${esc(item.tag)}</span>`:''}</div></div>`).join('')}</div>`:`<div class="empty-state"><h3>${esc(empty)}</h3><p>New shared records will appear here without invented activity.</p></div>`;}
  views.overview=function(){
    const openVotes=(state.proposals||[]).filter(p=>status(p.status)==='voting'),pending=(state.membershipRequests||[]).filter(x=>status(x.status)==='pending'),drafts=(state.transactions||[]).filter(x=>status(x.status)==='draft'),posts=(state.posts||[]).slice(0,4),communities=(state.communities||[]).length,services=(state.services||[]).slice(0,3),firstName=esc(state.user.name.split(' ')[0]),timeLabel=new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening';
    const attention=[...openVotes.slice(0,2).map(p=>({icon:'V',title:p.title,detail:`${p.scope||'society'} vote is open`,tag:'REVIEW & VOTE',tagClass:'green'})),...pending.slice(0,2).map(r=>({icon:'J',title:r.communityName||'Society join request',detail:'Awaiting authorized society review',tag:'PENDING',tagClass:'gold'})),...drafts.slice(0,2).map(t=>({icon:'₨',title:t.desc||'Transfer draft',detail:'No money moved',tag:'DRAFT',tagClass:'gold'}))];
    return `<section class="overview-hero"><div class="overview-copy"><div class="overview-kicker"><span>${timeLabel}, ${firstName}</span><b>${getScopeLabel()} world</b></div><h1>Everything nearby.<br><em>One place to act.</em></h1><p>See what needs attention, connect your skills, join decisions and follow proof without losing control of your identity or location.</p><div class="overview-hero-actions"><button class="primary" data-action="post">＋ Share an update</button><button class="secondary" data-view="feed">Open your feed</button></div></div><aside class="today-card"><small>YOUR NEXT MOVE</small><strong>${openVotes.length?`${openVotes.length} decision${openVotes.length===1?'':'s'} need review`:attention.length?'Review local activity':'Explore what is nearby'}</strong><p>${cloudReady()?'Shared account connected.':'Private preview records remain on this device.'}</p><button data-action="jarvis">Ask JARVIS to guide me →</button></aside></section>
      <div class="capability-strip"><span class="tag ${cloudReady()?'green':'gold'}">${cloudReady()?'CONNECTED ACCOUNT':'PRIVATE PREVIEW'}</span><b>${getScopeLabel()} scope</b><span>JARVIS can explain and draft. Only you can publish, vote or approve a transfer.</span></div>
      <div class="home-actions"><button data-action="post"><i>＋</i><b>Post</b><span>Problem, video or update</span></button><button data-view="map"><i>◎</i><b>Explore</b><span>People and action nearby</span></button><button data-view="governance"><i>✓</i><b>Decide</b><span>${openVotes.length} eligible vote${openVotes.length===1?'':'s'} open</span></button><button data-view="services"><i>↗</i><b>Work</b><span>Skills, jobs and services</span></button></div>
      <div class="dashboard-grid">${card('Focus now',recordList(attention,'Nothing urgent needs action'),5)}${card('Your network',`<div class="metric-row"><div class="metric"><small>Communities</small><b>${communities}</b></div><div class="metric"><small>Your posts</small><b>${(state.posts||[]).filter(p=>p.authorId===state.user.uid||p.name===state.user.name).length}</b></div><div class="metric"><small>Connections</small><b>${(state.connections||[]).length}</b></div></div><button class="ghost-btn" style="margin-top:10px" data-view="communities">Find your communities</button>`,3)}${card('JARVIS briefing',`<div class="briefing">${openVotes.length?`${openVotes.length} governance decision${openVotes.length===1?'':'s'} can use your attention. `:'No open vote is loaded. '}${pending.length?`${pending.length} society request${pending.length===1?' is':'s are'} pending. `:''}${drafts.length?`${drafts.length} transfer draft${drafts.length===1?' has':'s have'} moved no money. `:''}Ask me to open a workspace, explain visible evidence, or prepare a draft.</div><button class="action-btn" style="margin-top:10px" data-action="jarvis">Talk to JARVIS</button>`,4)}
        <section class="card span-8"><div class="card-head"><div class="card-title">Location & public action map</div><button class="ghost-btn" data-view="map">Open map</button></div><div class="card-body"><div class="map-shell real-map-shell"><div id="gaigsLeaflet"></div></div></div></section>${card('Latest in your world',recordList(posts.map(p=>({icon:(p.type||'P')[0],title:p.text||p.type||'Post',detail:`${p.scope||''} · ${p.location||''}`,tag:p.type||'POST'})),'Open the feed to discover source-linked updates'),4)}
        ${card('Work and services nearby',recordList(services.map(s=>({icon:'↗',title:s.title,detail:`${s.meta||'Open opportunity'} · ${s.person||'Community member'}`,tag:s.tag||'WORK',tagClass:'green'})),'Add your skills to receive better local matches'),6)}${card('Communities around you',`<div class="community-preview"><div><span>JMN</span><b>${esc(state.community||'Your society')}</b><small>${esc(state.user.city||'Your city')} · community workspace</small></div><button class="ghost-btn" data-view="communities">Open nearby</button></div><p class="muted">Membership, discussion, proposals and project proof stay connected to their exact community scope.</p>`,6)}
        ${card('Capability truth',`<div class="activity-list"><div class="activity-item"><div class="activity-icon">ID</div><div><b>Identity & shared data</b><p>${cloudReady()?'Connected; KYC status still controls governance eligibility.':'Private preview records on this device.'}</p></div></div><div class="activity-item"><div class="activity-icon">₨</div><div><b>Money settlement</b><p>Not connected. Drafts cannot leave the platform.</p></div></div><div class="activity-item"><div class="activity-icon">BC</div><div><b>Blockchain anchoring</b><p>${(state.transactions||[]).some(x=>x.blockchainTxHash)?'At least one receipt exists; inspect it.':'No confirmed anchor receipt.'}</p></div></div></div>`,12)}</div>`;
  };
  views.projects=function(){
    const items=state.projects||[];return `${pageHead('Projects & proof','Approved proposals become milestone records; evidence and verification remain linked.',`<button class="action-btn" data-action="project">＋ Create from approval</button>`)}<div class="capability-strip"><span class="tag ${cloudReady()?'green':'gold'}">${cloudReady()?'SHARED RECORDS':'OFFLINE RECORDS'}</span><b>${items.length} project${items.length===1?'':'s'}</b><span>Creating a record does not approve funds or verify completion.</span></div><div class="dashboard-grid">${items.length?items.map(project=>card(project.name,`<div class="meta-row"><span class="tag">${esc(project.status||'draft')}</span><span class="tag">Proposal ${esc(project.proposalId||'unlinked')}</span></div><p class="muted">${esc(project.milestones||'No milestones supplied.')}</p><div class="governance-proof"><b>Proof required</b><span>Milestone owner, receipt/evidence and a separate verifier are required before any release can be requested.</span></div>`,4)).join(''):`${card('No projects yet',`<div class="empty-state"><h3>Start from an approved proposal</h3><p>A project cannot manufacture its own authority or funding.</p></div>`,12)}`}</div>`;
  };
  projectForm=function(){const approved=(state.proposals||[]).filter(p=>status(p.status)==='approved');return `<form id="projectCreateForm" class="form-grid"><label>Approved proposal<select id="projectProposal" ${approved.length?'':'disabled'}>${approved.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}</option>`).join('')||'<option>No approved proposal available</option>'}</select></label><label>Project name<input id="projectName" maxlength="160" required></label><label>Project funding target (PKR)<input id="projectBudget" type="number" min="0" step="1" required value="0"></label><label>Milestones — one per line as “title | amount”<textarea id="projectMilestones" required placeholder="Procurement proof | 100000\nInstallation proof | 75000\nIndependent outcome check | 10000"></textarea></label><label>Responsible team description<input id="projectTeam" maxlength="240" required></label><button class="primary" ${approved.length?'':'disabled'}>Create linked project</button></form>`;};
  async function createProject(event){event.preventDefault();event.stopImmediatePropagation();const proposal=(state.proposals||[]).find(p=>String(p.id)===$('#projectProposal').value&&status(p.status)==='approved');if(!proposal)return toast('An approved proposal is required.');const id=`project_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`,budget=Number($('#projectBudget').value||0),milestones=$('#projectMilestones').value.split('\n').map(x=>x.trim()).filter(Boolean).map((line,index)=>{const parts=line.split('|');return {id:`${id}_m${index+1}`,title:parts[0].trim(),amount:Math.max(0,Number(parts[1]||0)),status:'planned',createdBy:fbAuth?.currentUser?.uid||state.user.uid||state.user.email};}),allocated=milestones.reduce((sum,item)=>sum+item.amount,0);if(allocated>budget)return toast('Milestone amounts cannot exceed the project funding target.');const record={id,proposalId:proposal.id,name:$('#projectName').value.trim(),budget,milestones,team:$('#projectTeam').value.trim(),createdBy:fbAuth?.currentUser?.uid||state.user.uid||state.user.email,scope:String(proposal.scope||'society').toLowerCase(),scopeId:proposal.scopeId||state.community,status:cloudReady()?'planned':'active',fundingStatus:'not_connected',settlementMode:'disabled',createdAt:new Date().toISOString()};try{if(cloudReady())await fbDb.collection('projects').doc(id).set({...record,createdAt:firebase.firestore.FieldValue.serverTimestamp()});state.projects.unshift(record);save();closeModal();navigate('projects');toast(cloudReady()?'Project shared and linked to the approved proposal.':'Project added to your private preview workspace.');}catch(error){toast(error.message||'Project creation failed.');}}
  views.profile=function(){
    const mine=(state.posts||[]).filter(p=>p.authorId===state.user.uid||p.name===state.user.name),memberships=(state.communities||[]).filter(c=>['active','joined'].includes(status(c.status))||c.ownerId===state.user.uid);
    return `${pageHead('Personal profile','Identity, skills, communities and privacy choices controlled by you.',`<button class="action-btn" data-action="editProfile">Edit profile</button>`)}<div class="dashboard-grid"><section class="card span-12"><div class="profile-banner"></div><div class="profile-info"><div class="profile-avatar">${esc(state.user.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</div><div class="profile-copy"><h2>${esc(state.user.name)}</h2><p>${esc(state.user.city||'City not set')}, ${esc(state.user.country||'Country not set')}</p><div class="skill-grid">${String(state.user.skills||'').split(',').filter(Boolean).map(x=>`<span class="skill-chip">${esc(x.trim())}</span>`).join('')||'<span class="muted">Add skills to improve matching.</span>'}</div></div></div></section>${card('My actual activity',`<div class="metric-row"><div class="metric"><small>Posts</small><b>${mine.length}</b></div><div class="metric"><small>Communities</small><b>${memberships.length}</b></div><div class="metric"><small>Applications</small><b>${(state.applications||[]).length}</b></div></div>`,6)}${card('Privacy summary',`<div class="briefing"><b>Exact device location:</b> local only unless you explicitly publish a community-center coordinate.<br><b>Post pins:</b> optional and rounded to about 100 m.<br><b>CNIC:</b> raw number is not retained by this browser flow.<br><b>JARVIS:</b> cannot publish, approve, vote or move funds.</div>`,6)}</div>`;
  };
  views.global=function(){
    const posts=(state.posts||[]).filter(p=>status(p.scope)==='global'),proposals=(state.proposals||[]).filter(p=>status(p.scope)==='global'),emergencies=window.GAIGSEmergencyRecords?.().filter(x=>status(x.scope)==='global')||[];
    const items=[...emergencies.map(x=>({icon:'!',title:x.title,detail:`Emergency · ${x.status}`,tag:x.status,tagClass:status(x.status)==='verified'?'green':'gold'})),...proposals.map(x=>({icon:'V',title:x.title,detail:`Proposal · ${x.status}`,tag:'GOVERNANCE'})),...posts.map(x=>({icon:'P',title:x.text,detail:`${x.type||'Post'} · ${x.location||''}`,tag:'POST'}))];
    return `${pageHead('Global pulse','Global-scope records from the connected network, with provenance and status—not a claim of universal truth.','')}<div class="capability-strip"><span class="tag ${cloudReady()?'green':'gold'}">${cloudReady()?'CONNECTED SCOPE':'OFFLINE SCOPE'}</span><b>${items.length} global record${items.length===1?'':'s'}</b><span>Country, city and society authority remains local.</span></div><div class="dashboard-grid">${card('Global records',recordList(items,'No global records loaded'),8)}${card('How JARVIS handles global information',`<div class="briefing">JARVIS should distinguish verified evidence, reported claims, community testimony and unverified content. It shows missing sources and uncertainty; it is not a single global truth authority.</div><button class="ghost-btn" style="margin-top:10px" data-action="jarvis">Ask about visible records</button>`,4)}</div>`;
  };
  views.crew=function(){
    const apps=state.applications||[];return `${pageHead('Founding crew','Apply to a clearly defined build, research, creator or field-pilot track.',`<button class="action-btn" data-action="crewApply">Apply</button>`)}<div class="capability-strip"><span class="tag gold">RECRUITMENT WORKSPACE</span><b>${apps.length} application${apps.length===1?'':'s'} on this account</b><span>No team size or open seat is invented.</span></div><div class="dashboard-grid">${['Engineering','Creators & Media','Research & Policy','Community Hubs'].map(track=>card(track,`<p class="muted">Applications enter a review queue. Access to code, data or community operations is granted separately and can expire.</p><button class="ghost-btn" data-action="crewApply">Apply to this track</button>`,3)).join('')}${card('My applications',recordList(apps.map(x=>({icon:'A',title:x.track,detail:x.expertise,tag:x.status||'SUBMITTED'})),'No applications submitted'),12)}</div>`;
  };
  const priorBindModal=bindModal;
  bindModal=function(){priorBindModal();const form=$('#projectCreateForm');if(form&&!form.dataset.projectBound){form.dataset.projectBound='1';form.addEventListener('submit',createProject,true);}};
  if(firebaseAvailable&&fbAuth)fbAuth.onAuthStateChanged(user=>{if(!user||!window.NDCONF?.firebaseProductionMode)return;fbDb.collection('projects').where('createdBy','==',user.uid).orderBy('createdAt','desc').limit(100).onSnapshot(snapshot=>{const remote=snapshot.docs.map(doc=>({id:doc.id,...doc.data(),createdAt:doc.data().createdAt?.toDate?.().toISOString()||''})),ids=new Set(remote.map(x=>x.id));state.projects=[...remote,...(state.projects||[]).filter(x=>!ids.has(x.id))];save();if(state.view==='projects')render();},error=>console.warn('[GAIGS] Projects unavailable:',error.message));});
  if(state.user)render();
})();
