/* Emergency workflow: report, independent verification, then relief-ledger creation. */
(function(){
  'use strict';
  const key='gaigsEmergenciesV1';let emergencies=JSON.parse(localStorage.getItem(key)||'[]'),unsubscribes=[];
  const cloudReady=()=>Boolean(firebaseAvailable&&window.NDCONF?.firebaseProductionMode===true&&fbAuth?.currentUser&&fbDb);
  const uid=()=>fbAuth?.currentUser?.uid||state.user?.uid||state.user?.email||'offline-reporter';
  const persist=()=>localStorage.setItem(key,JSON.stringify(emergencies));
  const statusClass=status=>status==='verified'?'green':status==='rejected'?'red':'gold';
  function emergencyCard(item){
    const own=item.createdBy===uid(),canVerify=cloudReady()&&!own&&item.status==='reported';
    return `<article class="proposal-item emergency-record"><div class="governance-record-head"><div><div class="meta-row"><span class="tag red">${esc(String(item.severity||'reported').toUpperCase())}</span><span class="tag ${statusClass(item.status)}">${esc(String(item.status||'reported').toUpperCase())}</span><span class="tag">${esc(item.scope||'city')}</span></div><h3>${esc(item.title)}</h3></div><span class="tag">${esc(item.locationLabel||'Location withheld')}</span></div><p class="muted">${esc(item.description||'')}</p><div class="metric-row"><div class="metric"><small>Independent verifications</small><b>${Number(item.verificationCount||0)} / 2</b></div><div class="metric"><small>Relief ledger</small><b>${item.status==='verified'?'OPEN · ZERO BALANCE':'NOT OPEN'}</b></div><div class="metric"><small>Settlement</small><b>NOT CONNECTED</b></div></div><div class="governance-proof"><b>Safety boundary</b><span>A verified incident may open a traceable account record. It does not create money or confirm a donation provider.</span></div><div class="rule-actions">${canVerify?`<button class="action-btn" data-emergency-verify="${esc(item.id)}">Verify as independent witness</button>`:''}<button class="mini-btn" data-emergency-open="${esc(item.id)}">Open evidence & ledger</button></div></article>`;
  }
  views.emergency=function(){
    const verified=emergencies.filter(x=>x.status==='verified').length;
    return `${pageHead('Emergency response','Report incidents, collect independent verification, and trace relief activity without inventing balances.',`<button class="action-btn" data-action="emergency">＋ Report incident</button>`)}<div class="capability-strip"><span class="tag ${cloudReady()?'green':'gold'}">${cloudReady()?'SHARED VERIFICATION':'OFFLINE REPORTING'}</span><b>${verified} verified incident${verified===1?'':'s'}</b><span>Real donations remain disabled until a regulated provider and webhooks are configured.</span></div><div class="dashboard-grid"><section class="span-8"><div class="proposal-list">${emergencies.length?emergencies.map(emergencyCard).join(''):'<div class="empty-state"><h3>No incident reports</h3><p>Create a report with evidence. An incident is not called verified until two independent eligible witnesses confirm it.</p></div>'}</div></section>${card('Emergency trust sequence',`<div class="activity-list">${[['1','Report','Location, severity, description and evidence.'],['2','Verify','Two independent verified accounts confirm the incident.'],['3','Open ledger','Server creates a zero-balance relief account record.'],['4','Fund safely','A regulated provider confirms donations by signed webhook.'],['5','Deliver & prove','Allocations, receipts, delivery evidence and disputes remain linked.']].map(x=>`<div class="activity-item"><div class="activity-icon">${x[0]}</div><div><b>${x[1]}</b><p>${x[2]}</p></div></div>`).join('')}</div>`,4)}</div>`;
  };
  emergencyForm=function(){return `<form id="emergencyCreateForm" class="form-grid"><label>Incident title<input id="emergencyName" maxlength="160" required></label><label>Severity<select id="emergencySeverity"><option value="critical">Critical</option><option value="high">High</option><option value="moderate">Moderate</option></select></label><label>Distribution scope<select id="emergencyScope"><option value="city">City</option><option value="country">Country</option><option value="global">Global</option></select></label><label>Location label<input id="emergencyLocation" value="${esc(state.user?.city||'')}" maxlength="180" required></label><label>Description and immediate needs<textarea id="emergencyDescription" maxlength="3000" required></textarea></label><label>Photo or video evidence<input id="emergencyMedia" type="file" accept="image/*,video/*" required></label><label class="consent"><input id="emergencyApproxLocation" type="checkbox"> Attach an approximate coordinate (about 100 m). Do not expose a private shelter or beneficiary address.</label><button class="primary" type="submit">Submit unverified report</button></form>`;};
  async function submitReport(event){
    event.preventDefault();event.stopImmediatePropagation();const file=$('#emergencyMedia').files[0];if(!file)return toast('Evidence is required.');if(file.size>100*1024*1024)return toast('Evidence file must be under 100 MB.');
    const share=Boolean($('#emergencyApproxLocation').checked&&Number.isFinite(Number(state.user?.lat))&&Number.isFinite(Number(state.user?.lng))),id=`emergency_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`,item={id,title:$('#emergencyName').value.trim(),severity:$('#emergencySeverity').value,scope:$('#emergencyScope').value,scopeId:$('#emergencyScope').value==='city'?state.user.city:$('#emergencyScope').value==='country'?state.user.country:'global',locationLabel:$('#emergencyLocation').value.trim(),description:$('#emergencyDescription').value.trim(),evidenceName:file.name,evidenceUrl:'',lat:share?Number(Number(state.user.lat).toFixed(3)):null,lng:share?Number(Number(state.user.lng).toFixed(3)):null,locationPrecision:share?'approximately_100m':'none',createdBy:uid(),status:'reported',verificationCount:0,createdAt:new Date().toISOString()};
    try{if(cloudReady()){const path=`users/${uid()}/emergencies/${id}/${file.name.replace(/[^a-z0-9._-]/gi,'_')}`,ref=fbStorage.ref(path);await ref.put(file);item.evidenceUrl=await ref.getDownloadURL();await fbDb.collection('emergencies').doc(id).set({...item,createdAt:firebase.firestore.FieldValue.serverTimestamp()});}else{item.evidenceUrl=file.size<=2*1024*1024?await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);}):'';emergencies.unshift(item);persist();}
      closeModal();navigate('emergency');toast(cloudReady()?'Incident submitted for independent verification.':'Incident saved locally; shared verification requires cloud mode.');
    }catch(error){toast(error.message||'Incident report failed.');}
  }
  async function verify(id){
    if(!cloudReady())return toast('Independent verification requires a verified cloud account.');
    try{await fbDb.collection('emergencies').doc(id).collection('verifications').doc(uid()).set({verifierId:uid(),statement:'I independently observed or reviewed the supplied incident evidence.',createdAt:firebase.firestore.FieldValue.serverTimestamp()});toast('Verification submitted. The server will evaluate the threshold.');}
    catch(error){toast(error.message||'Verification failed.');}
  }
  function openRecord(id){const item=emergencies.find(x=>x.id===id);if(!item)return;openModal(`<h2>${esc(item.title)}</h2><div class="rule-card"><p><b>Status:</b> ${esc(item.status)}</p><p><b>Evidence:</b> ${esc(item.evidenceName||'recorded')}</p><p><b>Relief account:</b> ${item.status==='verified'?`GAIGS-RELIEF-${esc(item.id.toUpperCase().slice(-10))} · zero balance until provider confirmation`:'Not created before verification'}</p><p><b>Public money moved:</b> none recorded</p></div>${item.evidenceUrl?`<a class="action-btn inline-link" href="${esc(item.evidenceUrl)}" target="_blank" rel="noopener">Open submitted evidence</a>`:''}`);}
  const priorBindModal=bindModal;
  bindModal=function(){priorBindModal();const form=$('#emergencyCreateForm');if(form&&!form.dataset.emergencyBound){form.dataset.emergencyBound='1';form.addEventListener('submit',submitReport,true);}};
  const priorBindDynamic=bindDynamic;
  bindDynamic=function(){priorBindDynamic();$$('[data-emergency-verify]').forEach(button=>button.addEventListener('click',()=>verify(button.dataset.emergencyVerify)));$$('[data-emergency-open]').forEach(button=>button.addEventListener('click',()=>openRecord(button.dataset.emergencyOpen)));};
  async function start(user){unsubscribes.forEach(stop=>stop());unsubscribes=[];if(!user||!window.NDCONF?.firebaseProductionMode)return;const profile=await fbDb.collection('publicProfiles').doc(user.uid).get().then(doc=>doc.exists?doc.data():{}).catch(()=>({})),parts=new Map(),specs=[['global','global'],profile.country&&['country',profile.country],profile.city&&['city',profile.city]].filter(Boolean),merge=()=>{const seen=new Set();emergencies=[...parts.values()].flat().filter(x=>!seen.has(x.id)&&seen.add(x.id)).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));persist();if(['emergency','overview','global'].includes(state.view))render();};specs.forEach(([scope,scopeId])=>{const keyPart=`${scope}:${scopeId}`,stop=fbDb.collection('emergencies').where('scope','==',scope).where('scopeId','==',scopeId).orderBy('createdAt','desc').limit(100).onSnapshot(snapshot=>{parts.set(keyPart,snapshot.docs.map(doc=>({id:doc.id,...doc.data(),createdAt:doc.data().createdAt?.toDate?.().toISOString()||''})));merge();},error=>console.warn(`[GAIGS] ${keyPart} emergencies unavailable:`,error.message));unsubscribes.push(stop);});}
  if(firebaseAvailable&&fbAuth)fbAuth.onAuthStateChanged(start);
  window.GAIGSEmergencyRecords=()=>emergencies.slice();
})();
