(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GAIGSMarketplaceLogic=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const requestTransitions={open:['offer_selected','canceled'],offer_selected:['in_progress','canceled'],selected:['in_progress','disputed'],in_progress:['submitted','disputed'],submitted:['completed','disputed'],disputed:['in_progress','canceled','resolved'],completed:[],canceled:[],resolved:[]};
  function canTransition(from,to){return (requestTransitions[String(from||'')]||[]).includes(String(to||''));}
  function validateRequest(input){const title=String(input.title||'').trim(),description=String(input.description||'').trim(),budgetMinor=Math.round(Number(input.budgetMinor));if(title.length<3||description.length<10)throw new Error('Title and description are required');if(!Number.isSafeInteger(budgetMinor)||budgetMinor<0)throw new Error('Budget must be a non-negative integer');return {...input,title:title.slice(0,160),description:description.slice(0,3000),budgetMinor};}
  function validateOffer(input){const amountMinor=Math.round(Number(input.amountMinor)),estimatedDays=Math.round(Number(input.estimatedDays)),message=String(input.message||'').trim();if(!Number.isSafeInteger(amountMinor)||amountMinor<=0)throw new Error('Offer amount must be positive');if(!Number.isInteger(estimatedDays)||estimatedDays<1||estimatedDays>365)throw new Error('Delivery time must be 1-365 days');if(message.length<5)throw new Error('Explain the offer');return {...input,amountMinor,estimatedDays,message:message.slice(0,1200)};}
  function rankRequests(requests,context={}){const skills=String(context.skills||'').toLowerCase().split(',').map(x=>x.trim()).filter(Boolean),city=String(context.city||'').toLowerCase();return (requests||[]).map(request=>{const text=`${request.title||''} ${request.description||''}`.toLowerCase(),skillScore=skills.filter(skill=>text.includes(skill)).length*30,cityScore=String(request.city||'').toLowerCase()===city?25:0,freshness=Math.max(0,20-Math.floor((Number(context.now||Date.now())-new Date(request.createdAt||0).getTime())/86400000));return {...request,matchScore:skillScore+cityScore+freshness};}).sort((a,b)=>b.matchScore-a.matchScore||new Date(b.createdAt||0)-new Date(a.createdAt||0));}
  return {requestTransitions,canTransition,validateRequest,validateOffer,rankRequests};
});
