/* Play-policy-facing privacy, session and account deletion controls. */
(function(){
  'use strict';
  const cloudReady=()=>Boolean(firebaseAvailable&&window.NDCONF?.firebaseProductionMode===true&&fbAuth?.currentUser&&fbFunctions);
  views.settings=function(){return `${pageHead('Settings & privacy','Control permissions, JARVIS context, sessions and account lifecycle.','')}<div class="dashboard-grid">${card('Privacy & permissions',settingsPrivacy(),6)}${card('JARVIS permissions',settingsJarvis(),6)}${card('Language & accessibility',settingsLanguage(),6)}${card('Security & account',`<div class="activity-list"><div class="activity-item"><div class="activity-icon">EV</div><div><b>Email verification</b><p>${fbAuth?.currentUser?.emailVerified?'Verified':'Required in production mode'}</p></div></div><div class="activity-item"><div class="activity-icon">KY</div><div><b>Identity review</b><p>${esc(state.user?.kycStatus||'Not completed')} · raw CNIC is never written to a public profile or blockchain.</p></div></div><div class="activity-item"><div class="activity-icon">DL</div><div><b>Download & deletion</b><p>Request account deletion in-app or from the public deletion page.</p></div></div></div><div class="rule-actions"><a class="ghost-btn" href="../privacy.html" target="_blank" rel="noopener">Privacy policy</a><a class="ghost-btn" href="../delete-account.html" target="_blank" rel="noopener">Deletion page</a><button class="danger-btn" data-delete-account>Delete my account</button></div>`,6)}${card('Important release boundary',`<div class="demo-banner">Real payments, crypto settlement and public-fund custody remain disabled until provider onboarding, jurisdiction review and independent security audit are complete.</div><p class="muted">Deleting an account removes profile and owned content. Narrow fraud-prevention or legally required financial records may be retained in pseudonymized form as disclosed in the privacy policy.</p>`,12)}</div>`;};
  function deletionModal(){openModal(`<h2>Delete your GAIGS account</h2><p class="muted">This disables sign-in immediately and queues profile, content and linked personal data for deletion. This cannot be undone.</p><form id="accountDeletionForm" class="form-grid"><label>Type DELETE to confirm<input id="deleteConfirm" required pattern="DELETE"></label><label class="consent"><input type="checkbox" required> I understand that my account and associated data will be deleted, subject only to disclosed legal/fraud-prevention retention.</label><button class="danger-btn" ${cloudReady()?'':'disabled'}>Permanently request deletion</button></form>${cloudReady()?'':'<div class="demo-banner">Connect the production account service to submit a deletion request.</div>'}`);}
  async function requestDeletion(event){event.preventDefault();event.stopImmediatePropagation();if($('#deleteConfirm').value!=='DELETE')return toast('Type DELETE exactly.');try{const callable=fbFunctions.httpsCallable('requestAccountDeletion'),result=await callable({});localStorage.clear();closeModal();toast(result.data?.message||'Deletion request submitted.');setTimeout(()=>location.reload(),1600);}catch(error){toast(error.message||'Deletion request failed. Sign in again and retry.');}}
  const baseBindDynamic=bindDynamic;
  bindDynamic=function(){baseBindDynamic();$$('[data-delete-account]').forEach(button=>button.addEventListener('click',deletionModal));};
  const baseBindModal=bindModal;
  bindModal=function(){baseBindModal();const form=$('#accountDeletionForm');if(form&&!form.dataset.bound){form.dataset.bound='1';form.addEventListener('submit',requestDeletion,true);}};
})();
