import { vault } from "./local-vault.js";
import { appendEvent, ensureDeviceIdentity, saveRecord, verifyEventSet } from "./ledger-core.js";
import { downloadBundle, exportSyncBundle } from "./mesh-core.js";

const $ = (selector, root = document) => root.querySelector(selector); const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]);
function toast(message, error = false) { const node = document.createElement("div"); node.className = `toast${error ? " error" : ""}`; node.textContent = message; $("#toasts").append(node); setTimeout(() => node.remove(), 4500); }
function shortHash(value = "") { return `${value.slice(0, 9)}…${value.slice(-6)}`; }

function setAdminView(page) { $$(".admin-view").forEach(node => node.classList.toggle("active", node.dataset.adminPage === page)); $$('[data-admin-view]').forEach(node => node.classList.toggle("active", node.dataset.adminView === page)); window.scrollTo({ top:0, behavior:"smooth" }); }

async function actionRecords() { return (await vault.list("records")).filter(record => record.recordType === "protocol-action").sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)); }
function actionCard(action) { return `<article class="protocol-card" data-action-id="${escapeHtml(action.id)}"><div class="protocol-state"><span>${escapeHtml(action.type)}</span><b>1 / ${action.threshold || 2} approvals</b></div><h3>${escapeHtml(action.reason)}</h3><p>Scope: ${escapeHtml(action.scope)} · Review/expiry: ${escapeHtml(action.expires)} · proposed on this device</p><div class="approval-track"><i class="approved"></i><i></i><i></i></div><div class="tile-actions"><button data-inspect-action="${escapeHtml(action.id)}">Inspect receipt</button><button data-approve-action="${escapeHtml(action.id)}">Approve from this device</button></div><small>Blocked: independent approval and configured executor required.</small></article>`; }
async function renderActions() { const actions = await actionRecords(); const fallback = { id:"preview-emergency", type:"emergency.freeze", scope:"global", reason:"Preview: freeze an exploited public executor while evidence is reviewed", expires:"Not executable", threshold:3 }; $("#protocolActions").innerHTML = [ ...actions, fallback ].map(actionCard).join(""); $("#overviewActions").innerHTML = actions.length ? actions.slice(0,2).map(actionCard).join("") : `<div class="empty-admin"><b>No signed local proposals</b><p>Create an action to see its immutable receipt and threshold state.</p></div>`; }

async function renderMetrics() { const [records, events] = await Promise.all([vault.list("records"), vault.list("events")]); $("#metricRecords").textContent = records.length; $("#metricEvents").textContent = events.length; const verification = await verifyEventSet(events); $("#metricIntegrity").textContent = verification.valid ? "all signatures valid" : `${verification.failures.length} failures`; $("#adminLedger").innerHTML = events.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,40).map(event => `<div class="receipt"><span class="receipt-icon">${event.type.includes("admin") || event.type.includes("protocol") ? "A" : "✓"}</span><span><b>${escapeHtml(event.type.replaceAll("."," "))}</b><small>${new Date(event.createdAt).toLocaleString()} · ${escapeHtml(event.scope)}</small></span><code>${shortHash(event.hash)}</code></div>`).join("") || `<div class="empty-admin"><p>No events yet.</p></div>`; }

async function verifyIntegrity() { const events = await vault.list("events"); const result = await verifyEventSet(events); const score = result.total ? Math.round(result.verified/result.total*100) : 100; $("#adminIntegrityScore").textContent = score; $("#adminIntegrityText").textContent = result.valid ? `${result.verified} signed event(s) verified` : `${result.failures.length} verification failure(s)`; $("#adminIntegrityDetail").textContent = result.valid ? "Hashes, device signatures and previous-event links are internally consistent." : result.failures.map(failure => failure.reason).join(" · "); toast(result.valid ? "Audit verification passed." : "Audit verification failed. Do not execute pending actions.", !result.valid); }

function openAction(prefill = {}) { const form = $("#adminActionForm"); form.reset(); if (prefill.type) form.elements.type.value = prefill.type; if (prefill.scope) form.elements.scope.value = prefill.scope; if (prefill.reason) form.elements.reason.value = prefill.reason; const future = new Date(Date.now()+30*864e5); form.elements.expires.value = future.toISOString().slice(0,10); $("#adminDialog").showModal(); }

async function createAction(event) { event.preventDefault(); const form = event.currentTarget, data = new FormData(form); const id=crypto.randomUUID(); const value={id,type:String(data.get("type")),scope:String(data.get("scope")),reason:String(data.get("reason")).trim(),expires:String(data.get("expires")),threshold:data.get("type")==="emergency.freeze"?3:2,status:"awaiting_approvals",proposerDevice:(await ensureDeviceIdentity()).fingerprint,approvals:1,createdAt:new Date().toISOString()}; const {record,event:ledgerEvent}=await saveRecord("protocol-action",value,{eventType:"admin.protocol_action_proposed",scope:value.scope,actorId:"local-steward"}); await vault.put("meta",{id:`approval:${record.id}:${value.proposerDevice}`,actionId:record.id,device:value.proposerDevice,eventId:ledgerEvent.id,createdAt:new Date().toISOString()}); $("#adminDialog").close(); await renderActions(); await renderMetrics(); toast("Protocol action signed. Execution remains blocked pending independent approvals and network configuration."); }

async function approveAction(id) { if (id === "preview-emergency") return toast("Preview actions cannot be approved. Create a real signed proposal first.",true); const identity=await ensureDeviceIdentity(); const approvalKey=`approval:${id}:${identity.fingerprint}`; if(await vault.get("meta",approvalKey)) return toast("This device has already provided its one permitted approval.",true); await vault.put("meta",{id:approvalKey,actionId:id,device:identity.fingerprint,createdAt:new Date().toISOString()}); await appendEvent("admin.protocol_action_approved",{actionId:id,scope:"global"},{actorId:"local-steward",scope:"global"}); toast("Approval signed. A different verified steward device is still required."); }

function moderationReview(id) { const details={"fundraiser":["Rain emergency fundraiser","A payment destination is visible but no verified custody policy or contract is configured."],"water-photo":["Water pressure photo","The image may disclose a house number. Redaction should be offered before any shared publication."],"creator-clip":["Imported creator clip","The Drive source is public, but participant consent and reuse rights have not been confirmed."]}; const [title,reason]=details[id]; openAction({type:"content.tombstone",scope:id==="creator-clip"?"society":"country",reason:`Review ${title}: ${reason}`}); }

function wire() { document.addEventListener("click",async event=>{ const nav=event.target.closest("[data-admin-view]"); if(nav)setAdminView(nav.dataset.adminView); const moderation=event.target.closest("[data-moderate]"); if(moderation)moderationReview(moderation.dataset.moderate); if(event.target.closest("#newProtocolAction"))openAction(); if(event.target.closest("#newPolicy"))openAction({type:"protocol.setting",scope:"global",reason:"Publish a revised moderation policy with evidence and a community review period."}); if(event.target.closest("#draftRole"))openAction({type:"role.assignment",scope:"city",reason:"Assign a time-bound operational clerk role after identity and scope verification."}); const approve=event.target.closest("[data-approve-action]"); if(approve)await approveAction(approve.dataset.approveAction); const inspect=event.target.closest("[data-inspect-action]"); if(inspect){ const action=(await actionRecords()).find(item=>item.id===inspect.dataset.inspectAction); toast(action?`Signed proposal ${action.id.slice(-12)} is waiting for threshold approval.`:"Preview has no executable receipt."); } const role=event.target.closest("[data-role-review]"); if(role)toast("Identity evidence is not configured. No role can be activated from a source-linked or claimable profile.",true); }); $("#adminActionForm").addEventListener("submit",createAction); $("#adminVerify").addEventListener("click",verifyIntegrity); $("#exportAudit").addEventListener("click",async()=>{downloadBundle(await exportSyncBundle());toast("Portable signed audit bundle exported.");}); }

async function bootstrap(){const identity=await ensureDeviceIdentity();$("#adminDevice").textContent=`Device ${identity.fingerprint}`;$("#adminClock").textContent=new Date().toLocaleString();wire();await renderActions();await renderMetrics();}
bootstrap().catch(error=>toast(error.message,true));
